name: Compile bufr lib

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Compile_bufr:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Install C++ Dependencies
        run: |
          sudo apt update
          sudo apt install pybind11-dev libeccodes-data rapidjson-dev
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: build application
        run: cd ./src/esoh/ingest/bufr && make
