name: Pip

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["flake8", "pytest"]
    branches: ["main"]
    tags:
      - "*"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install lib dep
        run: sudo apt update && sudo apt install libeccodes-data	rapidjson-dev	pybind11-dev libssl-dev

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


      - name: Build and install
        run: pip install --verbose .

      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          inputs: .
